### ISSUE TITLE
can not find my plugin!

### ISSUE THREAD

**Issue by niuemperor** [nodesource/npmsearch#48]
why i can't find my plugin?

can‘t find on this
http://cordova.apache.org/plugins/?q=foxit
https://npmsearch.com/?q=foxit

can find on this
https://www.npmjs.com/search?q=foxit
 @tmpvar

**Comment by sunnycupertino** [comment]
Yes ours has gone missing too https://github.com/sunnycupertino/cordova-plugin-admob-simple

**Comment by bnb** [comment]
@niuemperor I'm seeing the same results (actually 5 instead of just 4) on npmsearch.com that are appearing on the official npm site. Can you confirm that your plugin is still missing? I'd try to confirm, but not sure which one is yours. 

@sunnycupertino I'm seeing yours: https://npmsearch.com/?q=cordova-plugin-admob-simple

Can you confirm it's there?

**Comment by sunnycupertino** [comment]
Yes it's there now, thanks.

**Comment by niuemperor** [comment]
@bnb Yes it's there now, thanks very mush
